services:
  chu-ai:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./src/.env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
